market:
  collectors:
    api:
      endpoint:
        http:
          host: 0.0.0.0
          port: 8088
    enabled:
#      - tqxd
      - huobi
#      - binance
    huobi:
      clazz: com.tqxd.jys.collectors.impl.huobi.HuoBiKlineCollector
      config:
        host: api.huobiasia.vip
        path: /ws
        idle-time-out: 10000

      subscribe:
        kline:
          - btcusdt
          - ethusdt
    binance:
      clazz: com.tqxd.jys.collectors.impl.binance.BiNanceCollector
      config:
        proxy:
          switch: true
          host: 127.0.0.1
          port: 1080
        host: stream.binance.com
        port: 9443
        path: /ws
    tqxd:
      clazz: com.tqxd.jys.collectors.impl.tqxd.TqxdCollector
      config:
        host: market-pre.sgpexchange.com
        path: /
