market:
  collectors:
    api:
      endpoint:
        http:
          host: 0.0.0.0
          port: 8088
    enabled:
      - tqxd

    huobi:
      clazz: com.tqxd.jys.collectors.impl.huobi.HuoBiKlineCollector
      config:
        host: api.huobiasia.vip
        path: /ws
      subscribe:
        depth:
          - btcusdt
          - ETH-USDT
          - XRP-USDT
          - EOS-USDT
          - DOGE-USDT
          - HT-USDT
          - SHIB-USDT
          - ETC-USDT
          - ICP-USDT
        kline:
          - btcusdt
          - ETH-USDT
          - XRP-USDT
          - EOS-USDT
          - DOGE-USDT
          - HT-USDT
          - SHIB-USDT
          - ETC-USDT
          - ICP-USDT
        trade:
          detail:
            - BTC-USDT
            - BTC-USDT
            - ETH-USDT
            - XRP-USDT
            - EOS-USDT
            - DOGE-USDT
            - HT-USDT
            - SHIB-USDT
            - ETC-USDT
            - ICP-USDT

    binance:
      clazz: com.tqxd.jys.collectors.impl.binance.BiNanceCollector
      config:
        proxy:
          switch: true
          host: 127.0.0.1
          port: 1080
        host: stream.binance.com
        port: 9443
        path: /ws
      subscribe:
        depth:
          - BTC-USDT
    tqxd:
      clazz: com.tqxd.jys.collectors.impl.tqxd.TqxdCollector
      config:
        host: market-pre.sgpexchange.com
        path: /
      subscribe:
        kline:
          - AITD-USDT