market:
  collectors:
    enabled:
      - huobi
    huobi:
      clazz: com.tqxd.jys.collectors.impl.HuoBiKlineCollector
      net:
        host: api.huobiasia.vip
        path: /ws
      subscribe:
        depth:
          - BTC-USDT
        kline:
          - BTC-USDT
        trade:
          detail:
            - BTC-USDT

